
version: '3'

services:
  app-consumer:
    image: 'marlow-bank-consumer:latest'
    build:
      context: .
    container_name: app-consumer
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
    networks:
      - kafka-stack-docker-compose_default
    restart: always

networks:
  kafka-stack-docker-compose_default:
    external: true
