
version: '3'

services:
  app:
    image: 'marlow-bank:latest'
    build:
      context: .
    container_name: app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka1:19092
#      - host.docker.internal:29092
    networks:
      - kafka-stack-docker-compose_default
    restart: always

  PostgreSQL:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - "5431:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/db-prep.sql:/docker-entrypoint-initdb.d/db-prep.sql
    networks:
      - kafka-stack-docker-compose_default
    restart: always

#  zoo1:
#    image: confluentinc/cp-zookeeper:7.3.0
#    hostname: zoo1
#    ports:
#      - "2181:2181"
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zoo1:2888:3888
#    volumes:
#      - ./marlow-bank/zoo1/data:/data
#      - ./marlow-bank/zoo1/datalog:/datalog
#
#  kafka1:
#    image: confluentinc/cp-kafka:7.3.0
#    hostname: kafka1
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
#      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
#      KAFKA_BROKER_ID: 1
#      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#    volumes:
#      - ./marlow-bank/kafka1/data:/var/lib/kafka/data
#    depends_on:
#      - zoo1
networks:
  kafka-stack-docker-compose_default:
    external: true
